name: Push to s3 and  Deployment

on:
  push:
    branches:
    - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        - name: Use Node.js
          uses: actions/setup-node@v3
          with:
              node-version: '20.x'
        - run: sudo cd -D /mynodeapp      
        - run: sudo npm install -y
        - run: npm init
        - run: npm run build --if-present
        - run: npm test


  #    - name: Configure AWS Credentials
    #    uses: aws-actions/configure-aws-credentials@v4
   #     with:
     #      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #       aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
   #        aws-region: us-east-1

  #    - name: Deploy static site to S3 bucket
 #     - run: aws s3 sync . s3://forsampleapp --delete
